# 启动 MongoDB 和 MongoDB Express，但 MongoDB Express会遇到 mongo: Name does not resolve 错误
version: '3'
services:
  my-app:
    image: my-app:1.1 
    ports:
      - 3000:3000 
    depends_on:
      - mongodb 
    environment:
      - NODE_ENV=production 

  mongodb:
    image: mongo 
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=password 
    volumes:
      - mongo-data:/data/db 

  mongo-express:
    image: mongo-express 
    restart: always 
    ports:
      - 8080:8081 
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
      - ME_CONFIG_MONGODB_SERVER=mongodb 
      - ME_CONFIG_BASICAUTH_USERNAME=mick 
      - ME_CONFIG_BASICAUTH_PASSWORD=1234 

volumes:
  mongo-data:
    driver: local # 使用本地驱动持久化数据
